services:
  postgres:
    image: postgres:15
    container_name: pg_finpro
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:

      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 5s
      timeout: 3s
      retries: 10

  airflow:
    image: apache/airflow:2.9.3
    container_name: airflow_finpro
    restart: always
    command: >
      bash -lc "
      pip install --no-cache-dir -r /opt/airflow/app/requirements.txt &&
      airflow standalone
      "
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PG_DSN: "host=postgres user=postgres password=postgres dbname=ecommerce port=5432"
      PYTHONPATH: "/opt/airflow"
      GOOGLE_APPLICATION_CREDENTIALS: "/opt/airflow/app/jcdeah-006-e1b616f9939c.json"
    ports:
      - "8080:8080"  
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./app:/opt/airflow/app
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  pgdata:
